In [1]:
import re
import numpy as np
import datetime
import numpy as np

    
def check_funcion(fun):
    test_list = [3, 6, 10]
    NoneType = type(None)
    if isinstance(fun(test_list[1]), NoneType):
        return "You return 'None', try again!"
    else:
        results = []
    for i in range(len(test_list)):
        ch = fun(test_list[i])
        if np.all((ch == 1) + (ch == 0)) and np.all(np.sum(ch, 1) == np.arange(start=1, stop=test_list[i]+1)) and np.all(np.sum(ch, 0) == np.arange(start=test_list[i]+1, stop=1)):
            results.append(True)
    if all(results):
        return "Congrats, you passed the task! Submit it and see you tomorrow!"
    else:
        return "Try again, something is still not OK!"



In [7]:
# from test_your_code import check_funcion
import numpy as np

def half_xmas_tree(depth):
  # YOUR CODE GOES HERE
    x = np.ones((6,6))
    y = np.tril(x,k=0)
  # print(y)
    return y

print(check_funcion(half_xmas_tree))
print('\n',half_xmas_tree(6))

Congrats, you passed the task! Submit it and see you tomorrow!

 [[1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1.]]


C:\Users\Saurabh\anaconda3\lib\site-packages\ipykernel_launcher.py:16: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  app.launch_new_instance()
