### Day-3
#### Write a funtion called generate_matrix_9x9() that generates a 9x9 matrix with all elements equal 2 except the one in the middle which should be equal 0. If you are not a beginner, set only the boundary entries to 2 and the remaining ones to 0 :)



In [4]:
import re
import numpy as np
import datetime
import numpy as np

    
def check_funcion(fun):
    NoneType = type(None)
    if isinstance(fun(), NoneType):
        return "You return 'None', try again!"
    elif isinstance(fun(), type(np.array([]))):
        a = fun()
        results = []
        for i in range(len(a)):
            results.append(a[i][0]==2)
            results.append(a[8][0]==2)
            if i==0 or i==8:
                results.append(np.sum(a[i])==9*2)
            elif i==4:
                results.append(np.sum(a[i])==8*2 or np.sum(a[i])==4)
            else:
                results.append(np.sum(a[i])==9*2 or np.sum(a[i])==4)
        if all(results):
            return "Congrats, you passed the task! Submit it and see you tomorrow!"
        else:
            return "Try again, something is still not OK!"
    else:
        return "You should return a Numpy array!"

In [7]:
# from test_your_code import check_funcion
import numpy as np

def generate_matrix_9x9():
  # YOUR CODE GOES HERE
    arr = np.zeros(shape=(1,1))
    arr = np.pad(arr, pad_width=4, mode='constant', constant_values=2)
    return arr

print(check_funcion(generate_matrix_9x9))
print(generate_matrix_9x9())

Congrats, you passed the task! Submit it and see you tomorrow!
[[2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 0. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2.]]
